name = "paginazia"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./out"
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "production"

[env.preview.vars]
ENVIRONMENT = "preview"
